### ISSUE TITLE
summaryplot issue

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-utilities#16]
Hi, long time no see!

I tried to use summaryplot to get some plots, but the issue happened. I have updated ERT and summarploy to the least version and this binary never had the problem before.

Thanks!

```
Traceback (most recent call last):
  File "opm-utilities/summaryplot", line 52, in <module>
    import ert.ecl as ecl
  File "/usr/local/lib/python2.7/dist-packages/ert/__init__.py", line 120, in <module>
    from ert.util import Version
  File "/usr/local/lib/python2.7/dist-packages/ert/util/__init__.py", line 40, in <module>
    from cwrap import Prototype
  File "/usr/local/lib/python2.7/dist-packages/ert/cwrap/__init__.py", line 46, in <module>
    from .basecclass import BaseCClass
  File "/usr/local/lib/python2.7/dist-packages/ert/cwrap/basecclass.py", line 6, in <module>
    class BaseCClass(object):
  File "/usr/local/lib/python2.7/dist-packages/ert/cwrap/metacwrap.py", line 30, in __init__
    registerType(type_name, cls, is_return_type=is_return_type, storage_type=storage_type)
  File "/usr/local/lib/python2.7/dist-packages/ert/cwrap/prototype.py", line 20, in registerType
    raise PrototypeError("Type: '%s' already registered!" % type_name)
ert.cwrap.prototype.PrototypeError: Type: 'base_c_class' already registered!

```

**Comment by joakim-hove** [comment]
OK - this summaryplot utility does not get regular maintainence - will look into it; but not today I am afraid.

**Comment by qilicun** [comment]
@joakim-hove 
Thanks, take your time please.

**Comment by atgeirr** [comment]
Summaryplot is used in our starting-point tutorial:

http://opm-project.org/?page_id=197&page=6

If it breaks we must either fix it, or change the tutorial... (I assume for now that the release version of ert works with the current version of summaryploy)
